// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: allocation_description.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AllocationDescription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"requested_bytes")]
        public long RequestedBytes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"allocated_bytes")]
        public long AllocatedBytes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"allocator_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AllocatorName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"allocation_id")]
        public long AllocationId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"has_single_reference")]
        public bool HasSingleReference { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ptr")]
        public ulong Ptr { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
