// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: cost_graph.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CostGraphDef : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node")]
        public global::System.Collections.Generic.List<Node> Nodes { get; } = new global::System.Collections.Generic.List<Node>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Node : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"device")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Device { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"id")]
            public int Id { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"input_info")]
            public global::System.Collections.Generic.List<InputInfo> InputInfoes { get; } = new global::System.Collections.Generic.List<InputInfo>();

            [global::ProtoBuf.ProtoMember(5, Name = @"output_info")]
            public global::System.Collections.Generic.List<OutputInfo> OutputInfoes { get; } = new global::System.Collections.Generic.List<OutputInfo>();

            [global::ProtoBuf.ProtoMember(6, Name = @"temporary_memory_size")]
            public long TemporaryMemorySize { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"persistent_memory_size")]
            public long PersistentMemorySize { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"host_temp_memory_size")]
            [global::System.Obsolete]
            public long HostTempMemorySize { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"device_temp_memory_size")]
            [global::System.Obsolete]
            public long DeviceTempMemorySize { get; set; }

            [global::ProtoBuf.ProtoMember(16, Name = @"device_persistent_memory_size")]
            [global::System.Obsolete]
            public long DevicePersistentMemorySize { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"compute_cost")]
            public long ComputeCost { get; set; }

            [global::ProtoBuf.ProtoMember(14, Name = @"compute_time")]
            public long ComputeTime { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"memory_time")]
            public long MemoryTime { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"is_final")]
            public bool IsFinal { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"control_input", IsPacked = true)]
            public int[] ControlInputs { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class InputInfo : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"preceding_node")]
                public int PrecedingNode { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"preceding_port")]
                public int PrecedingPort { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class OutputInfo : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"size")]
                public long Size { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"alias_input_port")]
                public long AliasInputPort { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"shape")]
                public TensorShapeProto Shape { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"dtype")]
                public DataType Dtype { get; set; }

            }

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
