// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: device_attributes.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class InterconnectLink : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"device_id")]
        public int DeviceId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"strength")]
        public int Strength { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LocalLinks : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"link")]
        public global::System.Collections.Generic.List<InterconnectLink> Links { get; } = new global::System.Collections.Generic.List<InterconnectLink>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeviceLocality : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"bus_id")]
        public int BusId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"numa_node")]
        public int NumaNode { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"links")]
        public LocalLinks Links { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeviceAttributes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"device_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"memory_limit")]
        public long MemoryLimit { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"locality")]
        public DeviceLocality Locality { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"incarnation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Incarnation { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"physical_device_desc")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PhysicalDeviceDesc { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
