// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: graph_transfer_info.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferNodeInput : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node_id")]
        public int NodeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"output_port")]
        public int OutputPort { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferNodeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"node_id")]
        public int NodeId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"type_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TypeName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"soc_op_id")]
        public int SocOpId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"padding_id")]
        public int PaddingId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"input_count")]
        public int InputCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"output_count")]
        public int OutputCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferConstNodeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"node_id")]
        public int NodeId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"shape", IsPacked = true)]
        public long[] Shapes { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"data")]
        public byte[] Data { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"dtype")]
        public DataType Dtype { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferNodeInputInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node_id")]
        public int NodeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"node_input")]
        public global::System.Collections.Generic.List<GraphTransferNodeInput> NodeInputs { get; } = new global::System.Collections.Generic.List<GraphTransferNodeInput>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferNodeOutputInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node_id")]
        public int NodeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"max_byte_size", IsPacked = true)]
        public int[] MaxByteSizes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferGraphInputNodeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"shape", IsPacked = true)]
        public long[] Shapes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dtype")]
        public DataType Dtype { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferGraphOutputNodeInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"shape", IsPacked = true)]
        public long[] Shapes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dtype")]
        public DataType Dtype { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphTransferInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node_info")]
        public global::System.Collections.Generic.List<GraphTransferNodeInfo> NodeInfoes { get; } = new global::System.Collections.Generic.List<GraphTransferNodeInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"const_node_info")]
        public global::System.Collections.Generic.List<GraphTransferConstNodeInfo> ConstNodeInfoes { get; } = new global::System.Collections.Generic.List<GraphTransferConstNodeInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"node_input_info")]
        public global::System.Collections.Generic.List<GraphTransferNodeInputInfo> NodeInputInfoes { get; } = new global::System.Collections.Generic.List<GraphTransferNodeInputInfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"node_output_info")]
        public global::System.Collections.Generic.List<GraphTransferNodeOutputInfo> NodeOutputInfoes { get; } = new global::System.Collections.Generic.List<GraphTransferNodeOutputInfo>();

        [global::ProtoBuf.ProtoMember(5, Name = @"graph_input_node_info")]
        public global::System.Collections.Generic.List<GraphTransferGraphInputNodeInfo> GraphInputNodeInfoes { get; } = new global::System.Collections.Generic.List<GraphTransferGraphInputNodeInfo>();

        [global::ProtoBuf.ProtoMember(6, Name = @"graph_output_node_info")]
        public global::System.Collections.Generic.List<GraphTransferGraphOutputNodeInfo> GraphOutputNodeInfoes { get; } = new global::System.Collections.Generic.List<GraphTransferGraphOutputNodeInfo>();

        [global::ProtoBuf.ProtoMember(7)]
        public Destination destination { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Destination
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NOP")]
            Nop = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"HEXAGON")]
            Hexagon = 1,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
