// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: graph.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphDef : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node")]
        public global::System.Collections.Generic.List<NodeDef> Nodes { get; } = new global::System.Collections.Generic.List<NodeDef>();

        [global::ProtoBuf.ProtoMember(4, Name = @"versions")]
        public VersionDef Versions { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"version")]
        [global::System.Obsolete]
        public int Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"library")]
        public FunctionDefLibrary Library { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
