// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: remote_fused_graph_execute_info.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RemoteFusedGraphExecuteInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"remote_graph")]
        public GraphDef RemoteGraph { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"graph_input_node_name")]
        public global::System.Collections.Generic.List<string> GraphInputNodeNames { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"graph_output_node_name")]
        public global::System.Collections.Generic.List<string> GraphOutputNodeNames { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"executor_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ExecutorName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"serialized_executor_parameters")]
        public byte[] SerializedExecutorParameters { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"default_graph_input_tensor_shape")]
        public global::System.Collections.Generic.List<TensorShapeTypeProto> DefaultGraphInputTensorShapes { get; } = new global::System.Collections.Generic.List<TensorShapeTypeProto>();

        [global::ProtoBuf.ProtoMember(7, Name = @"default_graph_output_tensor_shape")]
        public global::System.Collections.Generic.List<TensorShapeTypeProto> DefaultGraphOutputTensorShapes { get; } = new global::System.Collections.Generic.List<TensorShapeTypeProto>();

        [global::ProtoBuf.ProtoContract()]
        public partial class TensorShapeTypeProto : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"dtype")]
            public DataType Dtype { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"shape")]
            public TensorShapeProto Shape { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
