// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: types.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Tensorflow
{

    [global::ProtoBuf.ProtoContract()]
    public enum DataType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INVALID")]
        DtInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_FLOAT")]
        DtFloat = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_DOUBLE")]
        DtDouble = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT32")]
        DtInt32 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT8")]
        DtUint8 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT16")]
        DtInt16 = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT8")]
        DtInt8 = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_STRING")]
        DtString = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_COMPLEX64")]
        DtComplex64 = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT64")]
        DtInt64 = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_BOOL")]
        DtBool = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QINT8")]
        DtQint8 = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QUINT8")]
        DtQuint8 = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QINT32")]
        DtQint32 = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_BFLOAT16")]
        DtBfloat16 = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QINT16")]
        DtQint16 = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QUINT16")]
        DtQuint16 = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT16")]
        DtUint16 = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_COMPLEX128")]
        DtComplex128 = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_HALF")]
        DtHalf = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_RESOURCE")]
        DtResource = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_VARIANT")]
        DtVariant = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT32")]
        DtUint32 = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT64")]
        DtUint64 = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_FLOAT_REF")]
        DtFloatRef = 101,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_DOUBLE_REF")]
        DtDoubleRef = 102,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT32_REF")]
        DtInt32Ref = 103,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT8_REF")]
        DtUint8Ref = 104,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT16_REF")]
        DtInt16Ref = 105,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT8_REF")]
        DtInt8Ref = 106,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_STRING_REF")]
        DtStringRef = 107,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_COMPLEX64_REF")]
        DtComplex64Ref = 108,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_INT64_REF")]
        DtInt64Ref = 109,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_BOOL_REF")]
        DtBoolRef = 110,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QINT8_REF")]
        DtQint8Ref = 111,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QUINT8_REF")]
        DtQuint8Ref = 112,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QINT32_REF")]
        DtQint32Ref = 113,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_BFLOAT16_REF")]
        DtBfloat16Ref = 114,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QINT16_REF")]
        DtQint16Ref = 115,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_QUINT16_REF")]
        DtQuint16Ref = 116,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT16_REF")]
        DtUint16Ref = 117,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_COMPLEX128_REF")]
        DtComplex128Ref = 118,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_HALF_REF")]
        DtHalfRef = 119,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_RESOURCE_REF")]
        DtResourceRef = 120,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_VARIANT_REF")]
        DtVariantRef = 121,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT32_REF")]
        DtUint32Ref = 122,
        [global::ProtoBuf.ProtoEnum(Name = @"DT_UINT64_REF")]
        DtUint64Ref = 123,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
