// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
using System.Xml.Linq;

namespace Tensorflow
{

  [global::ProtoBuf.ProtoContract()]
  public partial class BytesList : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public global::System.Collections.Generic.List<byte[]> Values { get; } = new global::System.Collections.Generic.List<byte[]>();

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class FloatList : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value", IsPacked = true)]
    public float[] Values { get; set; }

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class Int64List : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"value", IsPacked = true)]
    public long[] Values { get; set; }

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class Feature : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"bytes_list")]
    public BytesList BytesList
    {
      get => __pbn__kind.Is(1) ? ((BytesList)__pbn__kind.Object) : default;
      set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeBytesList() => __pbn__kind.Is(1);
    public void ResetBytesList() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__kind, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__kind;

    [global::ProtoBuf.ProtoMember(2, Name = @"float_list")]
    public FloatList FloatList
    {
      get => __pbn__kind.Is(2) ? ((FloatList)__pbn__kind.Object) : default;
      set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeFloatList() => __pbn__kind.Is(2);
    public void ResetFloatList() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__kind, 2);

    [global::ProtoBuf.ProtoMember(3, Name = @"int64_list")]
    public Int64List Int64List
    {
      get => __pbn__kind.Is(3) ? ((Int64List)__pbn__kind.Object) : default;
      set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeInt64List() => __pbn__kind.Is(3);
    public void ResetInt64List() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__kind, 3);

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class Features : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<string, Feature> feature { get; } = new global::System.Collections.Generic.Dictionary<string, Feature>();

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class FeatureList : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"feature")]
    public global::System.Collections.Generic.List<Feature> Features { get; } = new global::System.Collections.Generic.List<Feature>();

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class FeatureLists : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::ProtoBuf.ProtoMap]
    public global::System.Collections.Generic.Dictionary<string, FeatureList> feature_list { get; } = new global::System.Collections.Generic.Dictionary<string, FeatureList>();

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class Example : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"features")]
    public Features Features { get; set; }

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class SequenceExample : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"context")]
    public Features Context { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"feature_lists")]
    public FeatureLists FeatureLists { get; set; }

  }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
