#region License notice

/*
  This file is part of the Ceres project at https://github.com/dje-dev/ceres.
  Copyright (C) 2020- by David Elliott and the Ceres Authors.

  Ceres is free software under the terms of the GNU General Public License v3.0.
  You should have received a copy of the GNU General Public License
  along with Ceres. If not, see <http://www.gnu.org/licenses/>.
*/

#endregion

#region Using directives

using Ceres.Chess;

#endregion

namespace Ceres.MCTS.Managers.Limits
{
  /// <summary>
  /// Outputs generated by a TimeManager describing the
  /// optimal time strategy for the next move.
  /// </summary>
  public record ManagerGameLimitOutputs
  {
    /// <summary>
    /// The amount of time to target for the move initially.
    /// </summary>
    public SearchLimit LimitTarget { init; get; }

    /// <summary>
    /// Constructor.
    /// </summary>
    public ManagerGameLimitOutputs(SearchLimit baseTarget)
    {
      LimitTarget = baseTarget;

    }
    public override string ToString()
    {
      return $"<ManagerTimeOutputs {LimitTarget}>";
    }
  }


}
