// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Pblczero
{

  [global::ProtoBuf.ProtoContract()]
  public partial class EngineVersion : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"major")]
    public uint Major
    {
      get => __pbn__Major.GetValueOrDefault();
      set => __pbn__Major = value;
    }
    public bool ShouldSerializeMajor() => __pbn__Major != null;
    public void ResetMajor() => __pbn__Major = null;
    private uint? __pbn__Major;

    [global::ProtoBuf.ProtoMember(2, Name = @"minor")]
    public uint Minor
    {
      get => __pbn__Minor.GetValueOrDefault();
      set => __pbn__Minor = value;
    }
    public bool ShouldSerializeMinor() => __pbn__Minor != null;
    public void ResetMinor() => __pbn__Minor = null;
    private uint? __pbn__Minor;

    [global::ProtoBuf.ProtoMember(3, Name = @"patch")]
    public uint Patch
    {
      get => __pbn__Patch.GetValueOrDefault();
      set => __pbn__Patch = value;
    }
    public bool ShouldSerializePatch() => __pbn__Patch != null;
    public void ResetPatch() => __pbn__Patch = null;
    private uint? __pbn__Patch;

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class Weights : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"input")]
    public ConvBlock Input { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"residual")]
    public global::System.Collections.Generic.List<Residual> Residuals { get; } = new global::System.Collections.Generic.List<Residual>();

    [global::ProtoBuf.ProtoMember(11, Name = @"policy1")]
    public ConvBlock Policy1 { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"policy")]
    public ConvBlock Policy { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ip_pol_w")]
    public Layer IpPolW { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ip_pol_b")]
    public Layer IpPolB { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"value")]
    public ConvBlock Value { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ip1_val_w")]
    public Layer Ip1ValW { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ip1_val_b")]
    public Layer Ip1ValB { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ip2_val_w")]
    public Layer Ip2ValW { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"ip2_val_b")]
    public Layer Ip2ValB { get; set; }

    [global::ProtoBuf.ProtoMember(12, Name = @"moves_left")]
    public ConvBlock MovesLeft { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"ip1_mov_w")]
    public Layer Ip1MovW { get; set; }

    [global::ProtoBuf.ProtoMember(14, Name = @"ip1_mov_b")]
    public Layer Ip1MovB { get; set; }

    [global::ProtoBuf.ProtoMember(15, Name = @"ip2_mov_w")]
    public Layer Ip2MovW { get; set; }

    [global::ProtoBuf.ProtoMember(16, Name = @"ip2_mov_b")]
    public Layer Ip2MovB { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public partial class Layer : global::ProtoBuf.IExtensible
    {
      private global::ProtoBuf.IExtension __pbn__extensionData;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
          => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

      [global::ProtoBuf.ProtoMember(1, Name = @"min_val")]
      public float MinVal
      {
        get => __pbn__MinVal.GetValueOrDefault();
        set => __pbn__MinVal = value;
      }
      public bool ShouldSerializeMinVal() => __pbn__MinVal != null;
      public void ResetMinVal() => __pbn__MinVal = null;
      private float? __pbn__MinVal;

      [global::ProtoBuf.ProtoMember(2, Name = @"max_val")]
      public float MaxVal
      {
        get => __pbn__MaxVal.GetValueOrDefault();
        set => __pbn__MaxVal = value;
      }
      public bool ShouldSerializeMaxVal() => __pbn__MaxVal != null;
      public void ResetMaxVal() => __pbn__MaxVal = null;
      private float? __pbn__MaxVal;

      [global::ProtoBuf.ProtoMember(3, Name = @"params")]
      public byte[] Params
      {
        get => __pbn__Params;
        set => __pbn__Params = value;
      }
      public bool ShouldSerializeParams() => __pbn__Params != null;
      public void ResetParams() => __pbn__Params = null;
      private byte[] __pbn__Params;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConvBlock : global::ProtoBuf.IExtensible
    {
      private global::ProtoBuf.IExtension __pbn__extensionData;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
          => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

      [global::ProtoBuf.ProtoMember(1, Name = @"weights")]
      public Weights.Layer Weights { get; set; }

      [global::ProtoBuf.ProtoMember(2, Name = @"biases")]
      public Weights.Layer Biases { get; set; }

      [global::ProtoBuf.ProtoMember(3, Name = @"bn_means")]
      public Weights.Layer BnMeans { get; set; }

      [global::ProtoBuf.ProtoMember(4, Name = @"bn_stddivs")]
      public Weights.Layer BnStddivs { get; set; }

      [global::ProtoBuf.ProtoMember(5, Name = @"bn_gammas")]
      public Weights.Layer BnGammas { get; set; }

      [global::ProtoBuf.ProtoMember(6, Name = @"bn_betas")]
      public Weights.Layer BnBetas { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SEunit : global::ProtoBuf.IExtensible
    {
      private global::ProtoBuf.IExtension __pbn__extensionData;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
          => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

      [global::ProtoBuf.ProtoMember(1, Name = @"w1")]
      public Weights.Layer W1 { get; set; }

      [global::ProtoBuf.ProtoMember(2, Name = @"b1")]
      public Weights.Layer B1 { get; set; }

      [global::ProtoBuf.ProtoMember(3, Name = @"w2")]
      public Weights.Layer W2 { get; set; }

      [global::ProtoBuf.ProtoMember(4, Name = @"b2")]
      public Weights.Layer B2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Residual : global::ProtoBuf.IExtensible
    {
      private global::ProtoBuf.IExtension __pbn__extensionData;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
          => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

      [global::ProtoBuf.ProtoMember(1, Name = @"conv1")]
      public Weights.ConvBlock Conv1 { get; set; }

      [global::ProtoBuf.ProtoMember(2, Name = @"conv2")]
      public Weights.ConvBlock Conv2 { get; set; }

      [global::ProtoBuf.ProtoMember(3, Name = @"se")]
      public Weights.SEunit Se { get; set; }

    }

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class TrainingParams : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"training_steps")]
    public uint TrainingSteps
    {
      get => __pbn__TrainingSteps.GetValueOrDefault();
      set => __pbn__TrainingSteps = value;
    }
    public bool ShouldSerializeTrainingSteps() => __pbn__TrainingSteps != null;
    public void ResetTrainingSteps() => __pbn__TrainingSteps = null;
    private uint? __pbn__TrainingSteps;

    [global::ProtoBuf.ProtoMember(2, Name = @"learning_rate")]
    public float LearningRate
    {
      get => __pbn__LearningRate.GetValueOrDefault();
      set => __pbn__LearningRate = value;
    }
    public bool ShouldSerializeLearningRate() => __pbn__LearningRate != null;
    public void ResetLearningRate() => __pbn__LearningRate = null;
    private float? __pbn__LearningRate;

    [global::ProtoBuf.ProtoMember(3, Name = @"mse_loss")]
    public float MseLoss
    {
      get => __pbn__MseLoss.GetValueOrDefault();
      set => __pbn__MseLoss = value;
    }
    public bool ShouldSerializeMseLoss() => __pbn__MseLoss != null;
    public void ResetMseLoss() => __pbn__MseLoss = null;
    private float? __pbn__MseLoss;

    [global::ProtoBuf.ProtoMember(4, Name = @"policy_loss")]
    public float PolicyLoss
    {
      get => __pbn__PolicyLoss.GetValueOrDefault();
      set => __pbn__PolicyLoss = value;
    }
    public bool ShouldSerializePolicyLoss() => __pbn__PolicyLoss != null;
    public void ResetPolicyLoss() => __pbn__PolicyLoss = null;
    private float? __pbn__PolicyLoss;

    [global::ProtoBuf.ProtoMember(5, Name = @"accuracy")]
    public float Accuracy
    {
      get => __pbn__Accuracy.GetValueOrDefault();
      set => __pbn__Accuracy = value;
    }
    public bool ShouldSerializeAccuracy() => __pbn__Accuracy != null;
    public void ResetAccuracy() => __pbn__Accuracy = null;
    private float? __pbn__Accuracy;

    [global::ProtoBuf.ProtoMember(6, Name = @"lc0_params")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Lc0Params
    {
      get => __pbn__Lc0Params ?? "";
      set => __pbn__Lc0Params = value;
    }
    public bool ShouldSerializeLc0Params() => __pbn__Lc0Params != null;
    public void ResetLc0Params() => __pbn__Lc0Params = null;
    private string __pbn__Lc0Params;

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class NetworkFormat : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"input")]
    [global::System.ComponentModel.DefaultValue(InputFormat.InputUnknown)]
    public InputFormat Input
    {
      get => __pbn__Input ?? InputFormat.InputUnknown;
      set => __pbn__Input = value;
    }
    public bool ShouldSerializeInput() => __pbn__Input != null;
    public void ResetInput() => __pbn__Input = null;
    private InputFormat? __pbn__Input;

    [global::ProtoBuf.ProtoMember(2, Name = @"output")]
    [global::System.ComponentModel.DefaultValue(OutputFormat.OutputUnknown)]
    public OutputFormat Output
    {
      get => __pbn__Output ?? OutputFormat.OutputUnknown;
      set => __pbn__Output = value;
    }
    public bool ShouldSerializeOutput() => __pbn__Output != null;
    public void ResetOutput() => __pbn__Output = null;
    private OutputFormat? __pbn__Output;

    [global::ProtoBuf.ProtoMember(3, Name = @"network")]
    [global::System.ComponentModel.DefaultValue(NetworkStructure.NetworkUnknown)]
    public NetworkStructure Network
    {
      get => __pbn__Network ?? NetworkStructure.NetworkUnknown;
      set => __pbn__Network = value;
    }
    public bool ShouldSerializeNetwork() => __pbn__Network != null;
    public void ResetNetwork() => __pbn__Network = null;
    private NetworkStructure? __pbn__Network;

    [global::ProtoBuf.ProtoMember(4, Name = @"policy")]
    [global::System.ComponentModel.DefaultValue(PolicyFormat.PolicyUnknown)]
    public PolicyFormat Policy
    {
      get => __pbn__Policy ?? PolicyFormat.PolicyUnknown;
      set => __pbn__Policy = value;
    }
    public bool ShouldSerializePolicy() => __pbn__Policy != null;
    public void ResetPolicy() => __pbn__Policy = null;
    private PolicyFormat? __pbn__Policy;

    [global::ProtoBuf.ProtoMember(5, Name = @"value")]
    [global::System.ComponentModel.DefaultValue(ValueFormat.ValueUnknown)]
    public ValueFormat Value
    {
      get => __pbn__Value ?? ValueFormat.ValueUnknown;
      set => __pbn__Value = value;
    }
    public bool ShouldSerializeValue() => __pbn__Value != null;
    public void ResetValue() => __pbn__Value = null;
    private ValueFormat? __pbn__Value;

    [global::ProtoBuf.ProtoMember(6, Name = @"moves_left")]
    [global::System.ComponentModel.DefaultValue(MovesLeftFormat.MovesLeftNone)]
    public MovesLeftFormat MovesLeft
    {
      get => __pbn__MovesLeft ?? MovesLeftFormat.MovesLeftNone;
      set => __pbn__MovesLeft = value;
    }
    public bool ShouldSerializeMovesLeft() => __pbn__MovesLeft != null;
    public void ResetMovesLeft() => __pbn__MovesLeft = null;
    private MovesLeftFormat? __pbn__MovesLeft;

    [global::ProtoBuf.ProtoContract()]
    public enum InputFormat
    {
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_UNKNOWN")]
      InputUnknown = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_CLASSICAL_112_PLANE")]
      InputClassical112Plane = 1,
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_112_WITH_CASTLING_PLANE")]
      Input112WithCastlingPlane = 2,
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_112_WITH_CANONICALIZATION")]
      Input112WithCanonicalization = 3,
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_112_WITH_CANONICALIZATION_HECTOPLIES")]
      Input112WithCanonicalizationHectoplies = 4,
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_112_WITH_CANONICALIZATION_HECTOPLIES_ARMAGEDDON")]
      Input112WithCanonicalizationHectopliesArmageddon = 132,
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_112_WITH_CANONICALIZATION_V2")]
      Input112WithCanonicalizationV2 = 5,
      [global::ProtoBuf.ProtoEnum(Name = @"INPUT_112_WITH_CANONICALIZATION_V2_ARMAGEDDON")]
      Input112WithCanonicalizationV2Armageddon = 133,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OutputFormat
    {
      [global::ProtoBuf.ProtoEnum(Name = @"OUTPUT_UNKNOWN")]
      OutputUnknown = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"OUTPUT_CLASSICAL")]
      OutputClassical = 1,
      [global::ProtoBuf.ProtoEnum(Name = @"OUTPUT_WDL")]
      OutputWdl = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum NetworkStructure
    {
      [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_UNKNOWN")]
      NetworkUnknown = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_CLASSICAL")]
      NetworkClassical = 1,
      [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_SE")]
      NetworkSe = 2,
      [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_CLASSICAL_WITH_HEADFORMAT")]
      NetworkClassicalWithHeadformat = 3,
      [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_SE_WITH_HEADFORMAT")]
      NetworkSeWithHeadformat = 4,
      [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_ONNX")]
      NetworkOnnx = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PolicyFormat
    {
      [global::ProtoBuf.ProtoEnum(Name = @"POLICY_UNKNOWN")]
      PolicyUnknown = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"POLICY_CLASSICAL")]
      PolicyClassical = 1,
      [global::ProtoBuf.ProtoEnum(Name = @"POLICY_CONVOLUTION")]
      PolicyConvolution = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ValueFormat
    {
      [global::ProtoBuf.ProtoEnum(Name = @"VALUE_UNKNOWN")]
      ValueUnknown = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"VALUE_CLASSICAL")]
      ValueClassical = 1,
      [global::ProtoBuf.ProtoEnum(Name = @"VALUE_WDL")]
      ValueWdl = 2,
      [global::ProtoBuf.ProtoEnum(Name = @"VALUE_PARAM")]
      ValueParam = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MovesLeftFormat
    {
      [global::ProtoBuf.ProtoEnum(Name = @"MOVES_LEFT_NONE")]
      MovesLeftNone = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"MOVES_LEFT_V1")]
      MovesLeftV1 = 1,
    }

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class Format : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"weights_encoding")]
    [global::System.ComponentModel.DefaultValue(Encoding.Unknown)]
    public Encoding WeightsEncoding
    {
      get => __pbn__WeightsEncoding ?? Encoding.Unknown;
      set => __pbn__WeightsEncoding = value;
    }
    public bool ShouldSerializeWeightsEncoding() => __pbn__WeightsEncoding != null;
    public void ResetWeightsEncoding() => __pbn__WeightsEncoding = null;
    private Encoding? __pbn__WeightsEncoding;

    [global::ProtoBuf.ProtoMember(2, Name = @"network_format")]
    public NetworkFormat NetworkFormat { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public enum Encoding
    {
      [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
      Unknown = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"LINEAR16")]
      Linear16 = 1,
    }

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class OnnxModel : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"model")]
    public byte[] Model
    {
      get => __pbn__Model;
      set => __pbn__Model = value;
    }
    public bool ShouldSerializeModel() => __pbn__Model != null;
    public void ResetModel() => __pbn__Model = null;
    private byte[] __pbn__Model;

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue(DataType.UnknownDatatype)]
    public DataType data_type
    {
      get => __pbn__data_type ?? DataType.UnknownDatatype;
      set => __pbn__data_type = value;
    }
    public bool ShouldSerializedata_type() => __pbn__data_type != null;
    public void Resetdata_type() => __pbn__data_type = null;
    private DataType? __pbn__data_type;

    [global::ProtoBuf.ProtoMember(3, Name = @"input_planes")]
    [global::System.ComponentModel.DefaultValue("")]
    public string InputPlanes
    {
      get => __pbn__InputPlanes ?? "";
      set => __pbn__InputPlanes = value;
    }
    public bool ShouldSerializeInputPlanes() => __pbn__InputPlanes != null;
    public void ResetInputPlanes() => __pbn__InputPlanes = null;
    private string __pbn__InputPlanes;

    [global::ProtoBuf.ProtoMember(4, Name = @"output_value")]
    [global::System.ComponentModel.DefaultValue("")]
    public string OutputValue
    {
      get => __pbn__OutputValue ?? "";
      set => __pbn__OutputValue = value;
    }
    public bool ShouldSerializeOutputValue() => __pbn__OutputValue != null;
    public void ResetOutputValue() => __pbn__OutputValue = null;
    private string __pbn__OutputValue;

    [global::ProtoBuf.ProtoMember(5, Name = @"output_wdl")]
    [global::System.ComponentModel.DefaultValue("")]
    public string OutputWdl
    {
      get => __pbn__OutputWdl ?? "";
      set => __pbn__OutputWdl = value;
    }
    public bool ShouldSerializeOutputWdl() => __pbn__OutputWdl != null;
    public void ResetOutputWdl() => __pbn__OutputWdl = null;
    private string __pbn__OutputWdl;

    [global::ProtoBuf.ProtoMember(6, Name = @"output_policy")]
    [global::System.ComponentModel.DefaultValue("")]
    public string OutputPolicy
    {
      get => __pbn__OutputPolicy ?? "";
      set => __pbn__OutputPolicy = value;
    }
    public bool ShouldSerializeOutputPolicy() => __pbn__OutputPolicy != null;
    public void ResetOutputPolicy() => __pbn__OutputPolicy = null;
    private string __pbn__OutputPolicy;

    [global::ProtoBuf.ProtoMember(7, Name = @"output_mlh")]
    [global::System.ComponentModel.DefaultValue("")]
    public string OutputMlh
    {
      get => __pbn__OutputMlh ?? "";
      set => __pbn__OutputMlh = value;
    }
    public bool ShouldSerializeOutputMlh() => __pbn__OutputMlh != null;
    public void ResetOutputMlh() => __pbn__OutputMlh = null;
    private string __pbn__OutputMlh;

    [global::ProtoBuf.ProtoContract()]
    public enum DataType
    {
      [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_DATATYPE")]
      UnknownDatatype = 0,
      [global::ProtoBuf.ProtoEnum(Name = @"FLOAT")]
      Float = 1,
      [global::ProtoBuf.ProtoEnum(Name = @"FLOAT16")]
      Float16 = 10,
      [global::ProtoBuf.ProtoEnum(Name = @"BFLOAT16")]
      Bfloat16 = 16,
    }

  }

  [global::ProtoBuf.ProtoContract()]
  public partial class Net : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"magic", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint Magic
    {
      get => __pbn__Magic.GetValueOrDefault();
      set => __pbn__Magic = value;
    }
    public bool ShouldSerializeMagic() => __pbn__Magic != null;
    public void ResetMagic() => __pbn__Magic = null;
    private uint? __pbn__Magic;

    [global::ProtoBuf.ProtoMember(2, Name = @"license")]
    [global::System.ComponentModel.DefaultValue("")]
    public string License
    {
      get => __pbn__License ?? "";
      set => __pbn__License = value;
    }
    public bool ShouldSerializeLicense() => __pbn__License != null;
    public void ResetLicense() => __pbn__License = null;
    private string __pbn__License;

    [global::ProtoBuf.ProtoMember(3, Name = @"min_version")]
    public EngineVersion MinVersion { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"format")]
    public Format Format { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"training_params")]
    public TrainingParams TrainingParams { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"weights")]
    public Weights Weights { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"onnx_model")]
    public OnnxModel OnnxModel { get; set; }

  }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion